openapi: 3.0.0
info:
  version: "1.0.0"
  title: Swagger
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: amir.boussaadia@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:8980/
  - url: 'https://lecko.fr'
paths:
  /init:
    post:
      summary: init connection
      operationId: init
      responses:
        '200':
          description: successful operation
      requestBody:
        $ref: '#/components/requestBodies/Credentials'
  /save:
    get:
      summary: save
      operationId: save
      responses:
        '200':
          description: successful operation
  /emails:
    get:
      summary: get emails
      operationId: getEmails
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Email'
components:
  schemas:
    Email:
      type: object
      required:
        - name
        - from
        - content
        - date
      properties:
        name:
          type: string
        from:
          type: string
        content:
          type: string
        date:
          type: string
          format: date-time
    Credentials:
      type: object
      required:
        - clientId
        - clientSecret
        - tenant
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
        tenant:
          type: string
  requestBodies:
    Credentials:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Credentials'
      description: Credentials
      required: true